### ISSUE TITLE
Copy /lib/vendor to /vendor

### ISSUE THREAD

**Issue by pward123** [larryprice/novnc-core-autopublish#1]
At this location in the script https://github.com/larryprice/novnc-core-autopublish/blob/master/autopublish.sh#L36 you're copying the pre-transpiled code.

Would you consider changing this to 
`cp -rf $NOVNC_DIR/lib/vendor/* $NOVNC_CORE_DIR/vendor/`

**Comment by larryprice** [comment]
The reason this is currently being done is because that's how the script ends up from the transpile. Maybe I'll look into modifying `rfb.js` itself to address these issues.

**Comment by pward123** [comment]
I ended up having to manually change `require("../` to `require("./` in lib/inflator.js so I could eliminate the vendor folder.  Not exactly ideal, but I'd want to manually test any change to novnc before merging them into my project anyhow.

It's a shame that the novnc maintainers are so anti-npm.

Feel free to close this ticket since i have a workaround.

**Comment by larryprice** [comment]
OK - I'll keep this in mind for the future. I may end up adding in the same logic automatically in the autopublish script, though I'm not a huge fan of modifying the novnc code. Thanks again for the reports.
